### ISSUE TITLE
wrong line number in stack_test.go 

### ISSUE THREAD

**Issue by SwanSpouse** [pingcap/errors#17]
You may forget to change the line number in last commit, such as

https://github.com/pingcap/errors/blob/fc6e4ce558343e6eab2450e7653502fee61d9ad6/stack_test.go#L18

https://github.com/pingcap/errors/blob/fc6e4ce558343e6eab2450e7653502fee61d9ad6/stack_test.go#L24

And i have a question, what's the meaning of calling runtime.Caller(1) 

https://github.com/pingcap/errors/blob/fc6e4ce558343e6eab2450e7653502fee61d9ad6/stack_test.go#L27

Would You want to get the function of calling TestFrameLine in golang source codes ?

**Comment by lysu** [comment]
@SwanSpouse  

yes, last commit add a new import but not update the assert value, it's my fatal.

this test-case comes from upstream without modification(upstream also remove this and using go's new way to get frame https://github.com/pkg/errors/commit/4f47277723cbe176eaef3bccb66a69de7a531157#diff-dc00dbfbe2ed5a954c7447003e501d5eL11)

 `runtime.Caller(0) ` return call `runtime.Caller`'s frame --- just current frame,  `runtime.Caller(1) ` got call current method -- (call an anonymous function)'s frame.

```
// Caller reports file and line number information about function invocations on
// the calling goroutine's stack. The argument skip is the number of stack frames
// to ascend, with 0 identifying the caller of Caller.  (For historical reasons the
// meaning of skip differs between Caller and Callers.) The return values report the
// program counter, file name, and line number within the file of the corresponding
// call. The boolean ok is false if it was not possible to recover the information.
func Caller(skip int) (pc uintptr, file string, line int, ok bool) {
```

**Comment by lysu** [comment]
we also need port upstream's new commit to here, do you have interesting about it? @SwanSpouse  :laughing:

**Comment by SwanSpouse** [comment]
😃 certainly i'm interested, but i'm afraid i can't do it well. 
i'll have a try and new a pull request later 💪

**Comment by SwanSpouse** [comment]
@lysu 

I notice that upstream has changed back to the original way to get frame(https://github.com/pkg/errors/pull/189). 

Shall we use the original way or the new way to get frame ?
