### ISSUE TITLE
fetch upstream to make this repo update to date with upstream? 

### ISSUE THREAD

**Issue by feitian124** [pingcap/errors#38]
it is said pkg/errors merged to go standard lib but some useful feature like stack trace not.
this makes pkg/errors still useful and i see pingcap/errors forked from it at year 2018,
and since then does not sync with upstream, and both this and upsream have more than 20 commits.

do you think it is meaningful or needed if i would like to do the sync job? 

```diff
~/learn/go/errors @ master_upstream:master : git merge-base master master_upstream                                                                                                                                          
816c9085562cd7ee03e7f8188a1cfd942858cded

~/learn/go/errors @ master_upstream:master : git show 816c9085562cd7ee03e7f8188a1cfd942858cded 

commit 816c9085562cd7ee03e7f8188a1cfd942858cded (tag: pingcap_forked_here)
Author: Dave Cheney <dave@cheney.net>
Date:   Mon Mar 12 08:45:15 2018 +1100

    travis.yml: add Go 1.10 (#154)

diff --git a/.travis.yml b/.travis.yml
index 7ca408d..15e5a19 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,6 +7,7 @@ go:
   - 1.7.x
   - 1.8.x
   - 1.9.x
+  - 1.10.x
   - tip
 
 script:
```

**Comment by feitian124** [comment]
is there an owner(sig) of this repo? @tisonkun

**Comment by tisonkun** [comment]
From this file https://github.com/pingcap/community/blob/master/teams/tidb/README.md all tidb team members have privileges on this repo. I think almost @disksing @kennytm and I will put an eye on this repo's activity.

**Comment by tisonkun** [comment]
There is an analysis (in Chinese) by @disksing at https://docs.google.com/document/d/12CyoVUwQgIbYHKe5JnYkKzun6mH0dyU1q40UGJDRUDg . You may take a look to see where this repo to go.

**Comment by feitian124** [comment]
thanks, i will check.
i think stack trace is a must in large repo, i only found solution from pkg/errors have out of box support but seems inactive now.
so i wonder this forked rep0 can act as a better replacement.
for pingcap only is good, for general purpose is better.

**Comment by feitian124** [comment]
> thanks, i will check.
> i think stack trace is a must in large repo, i only found solution from pkg/errors have out of box support, but seems inactive now.
> so i wonder this forked rep0 can act as a better replacement.
> for pingcap only is good, for general purpose is better.

**Comment by disksing** [comment]
There are too many pingcap domain code changes. I think it is hard to update upstream now. I'm thinking if we can manage to keep only pingcap's error code handling in this repo and import `pkg/errors` in some way.
