### ISSUE TITLE
WithMessage and %q: not quoted

### ISSUE THREAD

**Issue by dolmen** [pingcap/errors#41]
`%q` doesn't quote errors wrapped with `errors.WithMessage`. We get the same output as `%s`.

This is inconsistent with the usual behavior of `%q` and the implementation for other wrappers in this package which quote correctly.

Example on the [Go Playground](https://go.dev/play/p/iIbzsNZIpUG):

```go
package main

import (
	stderrors "errors"
	"fmt"

	"github.com/pingcap/errors"
)

func main() {
	fmt.Printf("%s\n%[1]q\n", errors.WithMessage(stderrors.New(`quotes: ""`), `check "" quoting with %q`))
}
```

Output:
```
check "" quoting with %q: quotes: ""
check "" quoting with %q: quotes: ""
```

**Comment by dolmen** [comment]
Cause: implementation is the same for %s and %q:

https://github.com/pingcap/errors/blob/9687c2b0f87c5521d8c04dd1c03c33de3514f9c2/errors.go#L282

**Comment by disksing** [comment]
Thanks @dolmen I'm fixing it.
